### Get likes
GET http://localhost:8080

### Increment likes
POST http://localhost:8080/like
Content-Type: application/json

{
  "authorName": "Bruce Wayne",
  "userName": "John Smith",
  "amount": 2
}
