server:
  tomcat:
    accept-count: 200
    threads:
      max: 400

spring:
  application:
    name: test-transactional

  datasource:
    url: jdbc:postgresql://localhost:15432/somedb
    username: user
    password: secret
  sql:
    init:
      mode: always

  data:
    redis:
      port: 16379
      ssl:
        enabled: false

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: ${spring.application.name}
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoint:
    env:
      show-values: always
